from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

print(generator("Explain artificial intelligence to a 10 year old in a funny way"
, max_length=50)[0]["generated_text"])
# Output will be a continuation of the input text, generated by the GPT-2 model.